blog/urls.py
from django.contrib import admin
from django.urls import include, path
from blogapp.views import frontpage,about,create_post

urlpatterns = [
    path("admin/", admin.site.urls),
    path('about/',about,name='about'),
    path('create/', create_post, name='create_post'),
    path('',frontpage,name='frontpage'),
    path('',include('blogs.urls')),
    
]

blogapp/urls.py
from django.contrib import admin
from django.urls import path
from blog.blogapp.views import about, frontpage


urlpatterns = [
]

blogs/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<slug:slug>/',views.detail,name='post_detail'),
]

blogapp/models.py
from django.db import models

# Create your models here.

blogs/models.py
from django.db import models

    

class Post(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    intro = models.TextField()
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    author_name = models.CharField(max_length=100, blank=True)
    author_email = models.EmailField(blank=True)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post,related_name='comments',on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    body = models.TextField( )
    created_at = models.DateTimeField(auto_now_add=True) 

     

blogapp/forms.py
# forms.py

from django import forms
from blogs.models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'slug', 'intro', 'body', 'author_name', 'author_email']

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class': 'input', 'placeholder': 'Enter post title'})
        self.fields['slug'].widget.attrs.update({'class': 'input', 'placeholder': 'Enter post slug'})
        self.fields['intro'].widget.attrs.update({'class': 'textarea', 'placeholder': 'Write an introduction'})
        self.fields['body'].widget.attrs.update({'class': 'textarea', 'placeholder': 'Write your post content'})
        self.fields['author_name'].widget.attrs.update({'class': 'input', 'placeholder': 'Enter author name'})
        self.fields['author_email'].widget.attrs.update({'class': 'input', 'placeholder': 'Enter author email'})

blogs/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name','email','body')
        

blogapp/views.py
from django.shortcuts import redirect, render
from blogs.models import Post
from .forms import PostForm

def frontpage(request):
    posts = Post.objects.all()
    return render(request,'core/frontpage.html',{'posts':posts})

def about(request):
    return render(request,'core/about.html')

def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('frontpage')  # Redirect to homepage or list of posts
    else:
        form = PostForm()
    return render(request, 'core/create_post.html', {'form': form})

blogs/views.py
from django.shortcuts import redirect, render,get_object_or_404
from .models import Post
from .forms import CommentForm

def detail(request,slug):
    post = get_object_or_404(Post,slug=slug)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()

            return redirect('post_detail',slug=slug)
    else:
        form = CommentForm()

    form = CommentForm()
    return render(request,'blogs/detail.html',{'post':post,'form':form})

blogapp/templates/core/about.html
{% extends 'core/base.html' %}
{% block title %}About Us | {% endblock %}

{% block content %}
<section class="section">
    <div class="container">
        <h1 class="title">About Us</h1>
        
        <div class="content">
            <p>Welcome to our blog, a vibrant space where we delve into a myriad of topics that matter to you. From the latest advancements in technology and programming insights to explorations of cultural phenomena and lifestyle trends, our aim is to offer a diverse range of content that resonates with our readers. We believe in the power of storytelling and information-sharing to bridge gaps, inspire innovation, and foster connections among individuals from various backgrounds. Each article is crafted with care, aiming not only to inform but also to engage and provoke thought, encouraging our readers to explore new ideas and perspectives.</p>
            
            <p>This platform was born out of a passion for knowledge-sharing and community-building. In a world that is constantly evolving, we understand the importance of staying informed and adaptable. Our goal is to create a welcoming environment where readers can find valuable insights and practical resources that aid in personal and professional growth. We believe that everyone has a unique perspective to offer, and through our blog, we hope to cultivate a community of thinkers, creators, and learners who support and uplift one another. Whether you're here to learn something new, seek fresh ideas, or simply enjoy reading about diverse subjects, we’re thrilled to have you join us on this journey.</p>
            
            <p>Our dedicated team works tirelessly to ensure that our content is of the highest quality, well-researched, and relevant to our audience's interests. Each post undergoes a meticulous process of creation and review, guaranteeing that it meets our standards for accuracy and engagement. We also value the feedback, comments, and ideas from our readers, as they help us to continually improve and evolve. Our mission is not only to deliver engaging content but also to foster a sense of community among our readers, encouraging discussions and interactions that enrich the overall experience. Thank you for being part of our journey; we hope our blog adds a bit of value to your life every day and inspires you to explore the world around you!</p>
        </div>
    </div>
</section>
{% endblock %}

blogapp/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>{% block title %}{% endblock %} Blog</title>
        <link rel="stylesheet" href="https://unpkg.com/bulma@0.9.2/css/bulma.min.css">
        <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

        <style>
            /* Navbar and logo image adjustments */
            nav.navbar {
                height: 6rem !important;
                box-shadow: 0 1px 3px 0 rgba(0, 0, 0, .1), 0 1px 2px 0 rgba(0, 0, 0, .06) !important;
            }
            .navbar-item img {
                max-height: 4rem; /* Adjust height as needed */
                width: auto; /* Maintains aspect ratio */
            }
        </style>
    </head>
    <body>
        <nav class="navbar">
            <div class="container">
                <div class="navbar-brand">
                    <a class="navbar-item is-align-items-center" href="/">
                        <img src="{% static 'images/logo.png' %}" alt="Blog">
                        <strong class="ml-2"></strong>
                    </a>
                    <span class="navbar-burger burger" data-target="navbarMenu">
                        <span></span>
                        <span></span>
                        <span></span>
                    </span>
                </div>
                <div id="navbarMenu" class="navbar-menu">
                    <div class="navbar-end">
                        
                        <a href="/" class="navbar-item is-active is-size-5 has-text-weight-semibold">
                            Home
                        </a>
                        <a href="{% url 'create_post' %}" class="navbar-item is-size-5 has-text-weight-semibold">
                            Create New Post
                        </a>
                       
                        <a href="{% url 'about' %}" class="navbar-item is-size-5 has-text-weight-semibold">
                            About us
                        </a>
                    </div>
                </div>
            </div>
        </nav>
        <section class="section">
            <div class="container">
                {% block content %}
                {% endblock %}
            </div>
        </section>

        <footer class="footer">
            <div class="content has-text-centered">
                <p>
                    Copyright (c) 2024 - Blog
                </p>
            </div>
        </footer>
    </body>
</html>

blogapp/templates/core/create_post.html
{% extends 'core/base.html' %}
{% block title %}Create New Post{% endblock %}

{% block content %}
<section class="section">
    <div class="container">
        <h1 class="title">Create a New Post</h1>
        <form method="post">
            {% csrf_token %}
            <div class="field">
                <label class="label" for="id_title">Title</label>
                <div class="control">
                    {{ form.title }}
                </div>
            </div>
            <div class="field">
                <label class="label" for="id_slug">Slug</label>
                <div class="control">
                    {{ form.slug }}
                </div>
            </div>
            <div class="field">
                <label class="label" for="id_intro">Introduction</label>
                <div class="control">
                    {{ form.intro }}
                </div>
            </div>
            <div class="field">
                <label class="label" for="id_body">Body</label>
                <div class="control">
                    {{ form.body }}
                </div>
            </div>
            <div class="field">
                <label class="label" for="id_author_name">Author Name</label>
                <div class="control">
                    {{ form.author_name }}
                </div>
            </div>
            <div class="field">
                <label class="label" for="id_author_email">Author Email</label>
                <div class="control">
                    {{ form.author_email }}
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <button type="submit" class="button is-primary">Submit</button>
                </div>
            </div>
        </form>
    </div>
</section>
{% endblock %}

blogapp/templates/core/frontpage.html
{% extends 'core/base.html' %}
{% block title %}Home | {% endblock %}

{% block content %}

    <section class="hero ">
        <div class="hero-body">
        <div class="container">
            <section class="section">
                <div class="columns">
                    <div class="column is-8 is-offset-2">
                        {% for post in posts %}
                            <div class="content is-medium">
                                <a href="{% url 'post_detail' post.slug %}"
                                <h2 class="subtitle is-4">{{ post.created_at|date:'d-M-Y' }}</h2>
                                <h1 class="title">{{ post.title }}</h1>
                                <p>{{ post.intro }}</p>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </section>
        </div>
        </div>
    </section>

{% endblock %}

blogs/templates/blogs/detail.html
{% extends 'core/base.html' %}

{% block title %}{{post.title}} | {% endblock %}

{% block content %}


<section class="hero ">
    <div class="hero-body">
    <div class="container">
        <section class="section">
            <div class="columns">
                <div class="column is-8 is-offset-2">
                    
                    <div class="content is-medium">
                            <h2 class="subtitle is-4">{{ post.created_at|date:'d-M-Y' }}</h2>
                            <h1 class="title">{{ post.title }}</h1>
                            <p><strong>{{post.intro}}</strong></p>
                            <p>{{post.body}}</p>
                            <p>By author: {{post.author_name}}</p>

                            <hr>
                            <h2 class"subtitle is-4">Comments</h2>
                            {% for comment in post.comments.all %}
                                <article class="media box">
                                    <div class="media-content">
                                        <strong>{{comment.name}} </strong><small>{{comment.created_at|timesince}} ago</small><br>
                                        {{comment.body}}
                                    </div>
                                </article>
                            {% endfor %}
                            <section class="section">
                                <div class="columns">
                                    <div class="column is-8 is-offset-2">
                                        <h2 class="subtitle is-4">Leave a Comment</h2>
                                        <form method="post" class="mb-6">
                                            {% csrf_token %}
                                            {{form.as_p}}
                                            <div class="field">
                                                <div class="control">
                                                    <button class="button is-success">Submit Comment</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </section>
                            
                    </div>
                </div>
            </div>
        </section>
    </div>
    </div>
</section>

{% endblock %}